### ISSUE TITLE
What is your teaching plan for this year 2017?

### ISSUE THREAD

**Issue by EmbraceLife** [MorvanZhou/PyTorch-Tutorial#2]
Really appreciate for your effort in making wonderful tutorials on deep learning. Your work is outstanding, in its clarity and wide coverage of examples and libraries. I have explored a lot of deep learning tutorials and I like yours a lot. 

I sincerely hope your work will keep expanding and growing. I would like to know your teaching plan for the future, because I intend to spend lots of time studying your tutorials carefully. 

As you know, examples are great tools to learn, simple examples are necessary to get people started, and wide range and in-depth examples are also important to keep people motivated and going forward. I would like to see your tutorials and videos moving on to cover more examples while keeping the dataset small enough for Mac cpu to handle within reasonable time. 

I think you are already a great hit in deep learning tutorials in Chinese language, and keep going like this personally I believe you will be more famous than Siraj (who is currently one of the hottest deep learning evangelists)

All the best

**Comment by MorvanZhou** [comment]
Thank you for your great support, @EmbraceLife .
I'm not sure about my plan because I still have research to do as I am a PhD. Balancing my time between teaching and my research is hard. All I can do at the moment is to share what I have learned as much as I can to others who want to learn machine learning.
