### ISSUE TITLE
401_CNN.py

### ISSUE THREAD

**Issue by zhfff4869** [MorvanZhou/PyTorch-Tutorial#84]
I run it on WIN10.I have gotten the mnist.But when I run it,it says "RuntimeError: Dataset not found. You can use download=True to download it"

**Comment by Chester171** [comment]
#@
/# first, make sure that your conda is setup properly with the right environment

- # for that, check that `which conda`, `which pip` and `which python` 

> ### 

- [x] **_points_** to the

# right path. From a clean conda env, this is what you need to do

conda create --name maskrcnn_benchmark
source activate maskrcnn_benchmark

# this installs the right pip and dependencies for the fresh python
conda install ipython

# maskrcnn_benchmark and coco api dependencies
pip install ninja yacs cython matplotlib

# follow PyTorch installation in https://pytorch.org/get-started/locally/
# we give the instructions for CUDA 9.0
conda install pytorch-nightly -c pytorch

# install torchvision
cd ~/github
git clone https://github.com/pytorch/vision.git
cd vision
python setup.py install

# install pycocotools
cd ~/github
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
python setup.py build_ext install

# install PyTorch Detection
cd ~/github
git clone https://github.com/facebookresearch/maskrcnn-benchmark.git
cd maskrcnn-benchmark
# the following will install the lib with
# symbolic links, so that you can modify
# the files if you want and won't need to
# re-build it
python setup.py build develop

# or if you are on macOS
# MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py build develop

**Comment by tongbaochen** [comment]
您好，      您的邮件已收到。陈通宝广东工业大学

**Comment by li-phone** [comment]
你好，你的邮件已收到，稍后将会查看，尽快给你回复。
